version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'postgres_turbo'
    environment:
      POSTGRES_PASSWORD: 'secret_pass' # Обязательный параметр
      POSTGRES_DB: 'nestjs_blog' # Опционально: имя БД
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
